language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - bundle exec rspec --no-drb --format progress spec/
before_script:
  - mysql -e 'create database sulphur_test'
  - psql -c 'create database sulphur_test' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
